services:
  - type: web
    name: sub-bot
    env: python
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: CARGO_HOME
        value: /opt/render/project/src/.cargo
      - key: RUSTUP_HOME
        value: /opt/render/project/src/.rustup
